version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/deploy_laravel.sh
      timeout: 300
      runas: root
    - location: deploy/change_permissions.sh
      timeout: 300
      runas: root
